/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppDataTable: typeof import('./components/Globales/AppDataTable.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    copy: typeof import('./components/HelloWorld copy.vue')['default']
    HeaderMainLayout: typeof import('./components/Layouts/HeaderMainLayout.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Inicio: typeof import('./components/Inicio.vue')['default']
    Iniciocopy: typeof import('./components/Iniciocopy.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
